### ISSUE TITLE
Jobby not executing code with cron job

### ISSUE THREAD

**Issue by seanspeedymaui** [hellogerard/jobby#12]
I am able to run jobby.php from a shell and it works "php jobby.php" but when it's running from a cron job, the code inside doesn't get executed. 
I have verified in the logs jobby is being executed in cron every minute. I even added a php file with same format for cron job which sent out an email and it ran and generated the email every minute. 

Here is cron job format for jobby:

/usr/local/bin/php /home/mydir/public_html/jobby.php 1>> /dev/null 2>&1 
and another 
php -q /home/mydir/public_html/jobby.php 1>> /dev/null 2>&1

Here is a cron log entry showing jobby being run:

Apr 4 03:57:01 myserver crond[12094]: (myuser) CMD (/usr/local/bin/php /home/myuserl/public_html/jobby.php 1>> /dev/null 2>&1)

So we have verified that cron is working. Jobby work from the command line but doesn't work when being driven by cron. 

Anyone have any suggestions for modifying my configuration or anything else to try to get jobby to run via cron? I'm using Cpanel & CentOS.

**Comment by onovaes** [comment]
@seanspeedymaui  I have the same Problem.

How did you solve it?

**Comment by onovaes** [comment]
It's the same with me.

The shell and cron user are the same.

In cron master it runs the jobby.php file normally. All php functions of this file working normally both via sheel and via cron, but jobby only works via shell.

Via cron part of jobby does not work.

**Comment by shaveneLee** [comment]
the same with me..
