### ISSUE TITLE
Fixed vendor directory

### ISSUE THREAD

**Issue by hugsbrugs** [hellogerard/jobby#22]
Hi there,

first time I'm using composer to use jobby and as I didn't want to create a vendor directory, I added in my composer.json  : 

    "config": {
        "vendor-dir": "php/lib"
    },

But when using jobby I got : 

    PHP Fatal error:  require(): Failed opening required '/.../php/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /.../php/lib/hellogerard/jobby/src/Jobby/BackgroundJob.php on line 290

so I checked the line 290 : 

    require(dirname(dirname(dirname(dirname(dirname(__DIR__))))) . '/vendor/autoload.php');

and replace it by : 

    require(dirname(dirname(dirname(dirname(dirname(__DIR__))))) . '/lib/autoload.php');

to reflect my actual path. It works but there should be a better way of doing this by retrieving composer "vendor" directory set in config file and not hard writing it !

Thanks for the tool anayway !!

**Comment by hellogerard** [comment]
@hugsbrugs, Now that I think about it, I don't know of an easy way to reach into composer's config object other than reading `composer.json`. What do you think?

**Comment by hugsbrugs** [comment]
Hi @hellogerard ,

I've posted a question on stackoverflow  to move forward on this question and touch more people : 
http://stackoverflow.com/questions/31741949/composer-package-how-to-require-vendor-lib-autoload

Hope we will have some interesting points of view !

Cheers
