### ISSUE TITLE
If script runed under Jobby is unexpectedly die...

### ISSUE THREAD

**Issue by macklay** [hellogerard/jobby#25]
What we can do in this case? 
Manually check and remove .loc file is not cool, but Im cant find any checks for realy process running(and automatically remove .lock file if process with pid from lock file is not exist)

**Comment by hellogerard** [comment]
I'm not sure I understand your question. We haven't used actual [lock files for some time now](https://github.com/hellogerard/jobby/pull/1). We're using `flock()` which is robust to killed/crashed processes.
