### ISSUE TITLE
if not required option "runOnHost" is not set, job never not run

### ISSUE THREAD

**Issue by macklay** [hellogerard/jobby#26]
BackgroundJob::shouldRun method code:
```php
        $host = $this->helper->getHost();
        if (strcasecmp($this->config['runOnHost'], $host) != 0) {
            return false;
        }
```

**Comment by hellogerard** [comment]
`runOnHost` is optional. By default, it's set to the current host, so when `shouldRun` checks, it will match.

https://github.com/hellogerard/jobby/blob/1f731145ac6745f240a677543e15061acef698a6/src/Jobby/Jobby.php#L74
