### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by Zyles** [hellogerard/jobby#30]
Hi, I tried your sample script and changed the schedule to * * * * * so it runs every minute. But when I run: php jobby.php in console it does not do anything, no echos, no errors, no output, nothing.

I went into your source and double checked and it finds the job in $jobs at least as it is run.

But why can't I get it to run the job and execute the "ls" command?

I can execute exec() with a test script without any issues.

**Comment by Zyles** [comment]
Now I finally got some output in the log file and it shows this:

ERROR: Unable to open file (File: /tmp/commandexample.lck).

Which is odd because I have the same PHP app write to /tmp/ without any problems. Why would this happen?

When I run "php jobby.php" is it supposed to echo the output to the console if run is successful?

**Comment by Zyles** [comment]
Ok I got it to work with my app running jobby with the web server but I can't run it with cli, I assume there is some kind of permission problems going on.

**Comment by hellogerard** [comment]
Yes, the cron job will run as the user whose cron job it is. If you run it manually, it will run as you. Perhaps you don't have the same permission as the web server has for `/tmp`?

**Comment by OptimusCrime** [comment]
Not related to this software imo
