### ISSUE TITLE
Is it possible to make one job conditional on success of another?

### ISSUE THREAD

**Issue by vz28bh** [hellogerard/jobby#33]
This is a nice little tool but I was wondering if there was a way to make one job execute only if the another job was successful. For example, run job 1 at 7:00 and then run job 2 at 7:30 but only if job 1 was successful. A similar idea might be to not even specify a time for job 2 but just run it after job 1 but only if job 1 is successful. Currently I am doing this in code but it isn't very elegant.

**Comment by prentice87** [comment]
Well you either need to write to a DB or create a "success" file. If it exists just execute, otherwise don't. Basically a lock-file system but the opposite. I don't see how it is not elegant. That is exactly what you have temp folders for, right?

**Comment by hellogerard** [comment]
@vz28bh Check out the `haltDir` config option for a job. It wasn't put in for the your purpose, but it may help you.
