### ISSUE TITLE
Alternative configuration for windows servers.

### ISSUE THREAD

**Issue by LeonanCarvalho** [hellogerard/jobby#40]
How would a alternative configuration on Windows Task Manager for:

```
* * * * * cd /path/to/project && php jobby.php 1>> /dev/null 2>&1
```
I'm concerned about the performance of a script running every time.

**Comment by DannyBen** [comment]
Why not just set the cronjob to run every hour instead of every minute? (assuming you dont need the minute resolution)

    0 * * * * cd /path/to/project && php jobby.php 1>> /dev/null 2>&1

**Comment by hellogerard** [comment]
Yes, if you're concerned with performance, then you can of course run it less frequently. But then your jobs could run up to an hour later than in their schedule.

But I wouldn't be concerned with performance. If no jobs are schedule to run, it's a very small program. And jobby ensures that scripts do not start if they're already running.
